version: "3.7"
services:
  api:
    build: .
    image: 'school-system-app'
    container_name: 'school-system-container'
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-35-173-91-114.compute-1.amazonaws.com/denn02bb583hpr
      - SPRING_DATASOURCE_USERNAME=iqrwrusuriilgr
      - SPRING_DATASOURCE_PASSWORD=2c4f2835bba91b45c0b70f6e2b2d29151422e5aa2614c0940a6694d6c087c62b
  postgres:
    image: 'postgres:13-alpine'
    container_name: 'school-system-postgres-container'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=iqrwrusuriilgr
      - POSTGRES_PASSWORD=2c4f2835bba91b45c0b70f6e2b2d29151422e5aa2614c0940a6694d6c087c62b
      - POSTGRES_DB=denn02bb583hpr